#
# Dependabot configuration
#

# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - dependencies
    reviewers:
      - azure/psrule-rules-azure

  # Maintain dependencies for Dev Containers
  - package-ecosystem: devcontainers
    directory: '/'
    schedule:
      interval: daily
    labels:
      - dependencies
    reviewers:
      - azure/psrule-rules-azure
