# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Note:
# This files demonstrates using YAML-based rules.

---
# Synopsis: Azure resource must have an valid env tag set.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Org.Azure.Tags
spec:
  type:
  - 'Microsoft.Storage/storageAccounts'
  condition:
    allOf:
    - in:
        - 'prod'
        - 'test'
        - 'dev'
      field: 'tags.env'
